-- Camilla: run in Supabase SQL Editor
CREATE EXTENSION IF NOT EXISTS postgis;
CREATE EXTENSION IF NOT EXISTS pg_net;

CREATE TABLE IF NOT EXISTS public.scan_reports (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  local_id BIGINT,
  disease_id TEXT NOT NULL,
  timestamp TIMESTAMPTZ NOT NULL,
  latitude DOUBLE PRECISION NOT NULL,
  longitude DOUBLE PRECISION NOT NULL,
  user_text TEXT NOT NULL DEFAULT '',
  is_synced BOOLEAN NOT NULL DEFAULT true,
  geom GEOGRAPHY(POINT, 4326) GENERATED ALWAYS AS (
    ST_SetSRID(ST_MakePoint(longitude, latitude), 4326)::geography
  ) STORED,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.scan_reports
ADD COLUMN IF NOT EXISTS user_text TEXT NOT NULL DEFAULT '';

ALTER TABLE public.scan_reports ENABLE ROW LEVEL SECURITY;

-- Dev-friendly policy: tighten this for production.
DROP POLICY IF EXISTS "allow_insert_for_anon_phase3" ON public.scan_reports;
CREATE POLICY "allow_insert_for_anon_phase3"
ON public.scan_reports
FOR INSERT
TO anon, authenticated
WITH CHECK (true);

CREATE OR REPLACE FUNCTION public.notify_new_scan()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
AS $$
DECLARE
  request_id bigint;
BEGIN
  SELECT net.http_post(
    url := 'https://vkzpthcttutqoiwmfyqd.supabase.co/functions/v1/new-scan-alert',
    headers := jsonb_build_object(
      'Content-Type', 'application/json'
    ),
    body := jsonb_build_object('record', row_to_json(NEW))
  ) INTO request_id;

  RAISE LOG 'new-scan-alert request id: %', request_id;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_notify_new_scan ON public.scan_reports;
CREATE TRIGGER trg_notify_new_scan
AFTER INSERT ON public.scan_reports
FOR EACH ROW
EXECUTE FUNCTION public.notify_new_scan();
